import { GLOBAL_DEFAULTS } from "./GLOBAL_DEFAULTS";
import { VENDOR_DEFAULTS } from "./VENDOR_DEFAULTS";
import { VALID_LOADER_NAMES } from "./VALID_LOADER_NAMES";

const CONSTANTS = {
  GLOBAL_DEFAULTS,
  VENDOR_DEFAULTS,
  VALID_LOADER_NAMES,
};

export { CONSTANTS };
